### ISSUE TITLE
Missing License?

### ISSUE THREAD

**Issue by cpu** [mholt/acme#1]
:wave: If this repo is forked from Lego, should it also be licensed under MIT to match https://github.com/go-acme/lego/blob/master/LICENSE ? If not, what is the license?

Thanks!

**Comment by mholt** [comment]
Hey @cpu! How'd you find this repo so fast? 🤔  Are you interested in using it? 😃 

I'll definitely be adding a license as soon as it's ready to use! Probably will be the Apache license.

**Comment by cpu** [comment]
> Hey @cpu! How'd you find this repo so fast? thinking Are you interested in using it? smiley

I watch a lot of ACME client repos :blush: I think I saw this via certmagic. I use Lego presently for personal stuff but would consider your fork in the future when it's more mature/stable.

> I'll definitely be adding a license as soon as it's ready to use! Probably will be the Apache license.

Since your fork contains Lego code that was licensed as MIT aren't you under an obligation to meet the requirements of that license or re-license it under something compatible (like Apache?). Adding the original MIT license back seems like a quick fix that would respect the contributions made to Lego that you're building on.

**Comment by mholt** [comment]
Cool.

> Since your fork contains Lego code that was licensed as MIT aren't you under an obligation to meet the requirements of that license or re-license it under something compatible (like Apache?). Adding the original MIT license back seems like a quick fix that would respect the contributions made to Lego that you're building on.

Yeah, I'm aware of that. I am actually in the process of rewriting the whole thing, so I won't be sharing from the upstream code base. But as of today anyway it seems more likely that this will be gradual, so I'll probably add the licenses soon. (Do I just add both then?)

**Comment by cpu** [comment]
>  I am actually in the process of rewriting the whole thing, so I won't be sharing from the upstream code base.

Gotcha, that makes sense.

> But as of today anyway it seems more likely that this will be gradual, so I'll probably add the licenses soon. 

Right, as of today there's definitely code from Lego in the repo without the MIT license being honoured. I spot-checked https://github.com/mholt/acme/blob/23a2cbcb8cced93226fed3287590b19a575242e2/acme/api/account.go against https://github.com/go-acme/lego/blob/19f6a8c868a169bbc3ec09555153c54b6dffbcf9/acme/api/account.go to be sure.

>  (Do I just add both then?)

**Comment by mholt** [comment]
> Right, as of today there's definitely code from Lego in the repo without the MIT license being honoured.

Yes, that's because it's a fork, but I needed a place to push this while I was in the process of tearing it down before I started building it up again. I'll push licenses soon, but right now it doesn't work, and nobody should be using it. I just needed a remote for the Go module madness that I've been fighting locally during the transition.

**Comment by cpu** [comment]
Thanks for adding the MIT license again. Much appreciated!
